# Generated by Django 4.2.10 on 2024-02-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
                ('text', models.TextField(max_length=100000)),
            ],
        ),
        migrations.DeleteModel(
            name='Calculate',
        ),
    ]
